### ISSUE TITLE
I got errors when training the code

### ISSUE THREAD

**Issue by jinzhuwei** [MinkaiXu/GeoDiff#26]
**When loading the dataset, the code runs until train_set = ConformationDataset(config.dataset.train, transform=transforms) an error occurs**

Traceback (most recent call last):
  File "/storage/weijinzhu/GeoDiff-main/train.py", line 60, in <module>
    train_set = ConformationDataset(config.dataset.train, transform=transforms)
  File "/storage/weijinzhu/.conda/envs/geodiff/lib/python3.7/typing.py", line 819, in __new__
    obj = super().__new__(cls)
TypeError: Can't instantiate abstract class ConformationDataset with abstract methods get, len

**Comment by caiyingchun** [comment]
I got the same error.
